#!/bin/bash
. "${WMII_CONFPATH%%:*}/statusbar.conf"
THEME=SW
SYMBOL=266a

requires amixer || exit 97

if sb_ready 1; then
    lck ${LOCK_SB_MODULE} on
    read vol mute <<< "$(eval ${VOLUMESTATUS})"

    case ${BUTTON} in
        ${MOUSE_L}) eval ${VOLUMETOGGLE};;
        ${MOUSE_U}) eval ${VOLUMEUP};;
        ${MOUSE_D}) eval ${VOLUMEDOWN};;
    esac

    if [ "${mute}" == "off" ]; then
        sb_escalate CRIT
    fi

    DATA=${vol}
    sb_write_cache "${DATA}"

    lck ${LOCK_SB_MODULE} off
fi
sb_read_cache
