#!/bin/bash
. "${WMII_CONFPATH%%:*}/statusbar.conf"
THEME=HW
SYMBOL=2622
SYMBOL=23E3 #. Benzene

requires acpi || exit 97

acpi 2>&1|grep -q 'No support'
test $? -ne 0 || exit 1

if sb_ready 16; then
    lck ${LOCK_SB_MODULE} on
    acpi -bi > ${SB_STAGE_F}

    battery_life=
    battery_state=$(awk -F '[ ,]*' 'NR==1{print(tolower($3))}' ${SB_STAGE_F})
    battery_charge=$(awk -F '[ ,%]*' 'NR==1{print$4}' ${SB_STAGE_F})

    if [ $(sb_battery_state ${MOUSE_L}) -eq 1 ]; then
        battery_life=$(awk 'NR==2{printf" ~%s(%s/%s)",$13,$10,$5}' ${SB_STAGE_F});
    fi

    if [ "${battery_state}" == "charging" ]; then
        battery_state=' +'
    elif [ "${battery_state}" == "full" ]; then
        battery_state=
        battery_charge=
        sb_escalate GOOD
    elif [ "${battery_state}" == "discharging" ]; then
        battery_state=' -'
    elif [ "${battery_state}" == "unknown" ]; then
        battery_state=' -'
    fi

    if [ ${battery_charge} -lt 10 ]; then
        sb_escalate CRIT
    elif [ ${battery_charge} -lt 20 ]; then
        sb_escalate WARN
    elif [ ${battery_charge} -gt 97 ]; then
        sb_escalate GOOD
    fi

    test -z "${battery_charge}" || battery_charge="${battery_charge}%"
    sb_write_cache "${battery_state}${battery_charge}${battery_life}"
    lck ${LOCK_SB_MODULE} off
fi
sb_read_cache
